name: Count lines

on:
  workflow_dispatch:

jobs:
  Count-Code:
   runs-on: Ubuntu-latest
   steps:
   - uses: actions/checkout@v4
   - name: Count Lines of Code
     run: |
        LINE_COUNT=$(find . -name "*.cs" -exec cat {} + | wc -l)
          echo "Total lines of code in .cs files: $LINE_COUNT"

  
