name: test

on: 
  push:
  workflow_dispatch:

jobs:
  Build-Project:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
    - uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4.1.0
      with:
        dotnet-version: '8'
        
    - name: Build-project
      run: dotnet publish gitdemo.sln --output ./build

  
    - name: Upload artifact
      uses: actions/upload-artifact@v4.3.3
      with: 
          name: build-artifact
          path: ./build
    - name: List all
      run: ls -R ./build

    - name: Download artifact
      uses: actions/download-artifact@v4.1.8
      with:
         name: build-artifact
         path: ./build
    - name: List all
      run: ls -R ./build
    
      
  Run-Tests:
    runs-on: ubuntu-latest
    needs: [Build-Project]
    
    steps:
    - uses: actions/checkout@v4  
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0'
    - name: Run-tests
      run: dotnet test --no-build --logger "console;verbosity=detailed"
