name: Test

on: 
  push:
  workflow_dispatch:

jobs:      
  Run-Tests:
    runs-on: ubuntu-latest  
    
    steps:
    - uses: actions/checkout@v4  
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0'
        
    - name: Build-project
      run: dotnet build
      
    - name: Check-for-tests
      run: dotnet test --no-build --list-tests
      
    - name: Run-tests
      run: dotnet test --no-build --logger "console;verbosity=detailed"
    
      
