name: Update Database

on:
  workflow_dispatch:

jobs:
  Update-Local-Database:
    runs-on: windows-latest
         
    steps:
    - name: Checkout-Repository
      uses: actions/checkout@v4

    - name: Setup-Repository
      uses: actions/setup-dotnet@v4
      with: 
        dotnet-version: 8.0
        
    - name: Install dotnet-ef tool
      run: dotnet tool install --global dotnet-ef
      
    - name: Build
      run: dotnet build BudgetBuddy.Api/BudgetBuddy.Api.csproj

    - name: Update-Database
      run: dotnet ef database update --project ./source/repos/BudgetBuddy/BudgetBuddy/BudgetBuddy.Api/BudgetBuddy.Api.csproj

    - name: SuccessMessage
      if: success()
      run: echo "Everything went okay, check your local database for changes"

    - name: FailureMessage
      if: failure()
      run: echo "An error has occured when trying to update your database"
    
    
    
