name: Update Database

on:
  workflow_dispatch:

jobs:
  Update-Local-Database:
    strategy:
      matrix:
        op-system: ['ubuntu-latest', 'windows-latest']
    runs-on: ${{matrix.op-system}}
         
    steps:
    - name: Checkout-Repository
      uses: actions/checkout@v4

    - name: Setup-Repository
      uses: actions/setup-dotnet@v4
      with: 
        dotnet-version: 9.0.0

    - name: Build
      run: dotnet build

    - name: Update-Database
      run: dotnet ef database update

    - name: SuccessMessage
      if: success()
      run: echo "Everything went okay, check your local database for changes"

    - name: FailureMessage
      if: failure()
      run: echo "An error has occured when trying to update your database"
    
    
    
